name: Deploy to EC2 on push

on:
  push:
    branches:
      - origin  # or your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@ec2-3-86-198-236.compute-1.amazonaws.com << 'EOF'
            [ ! -d "/home/user/app/.git" ] && git clone https://github.com/Oluwaseun186/compose-up.git /home/user/app
            cd /home/user/app
            docker compose down
            docker compose up -d --build
          EOF
